### ISSUE TITLE
Getting this error: CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double"

### ISSUE THREAD

**Issue by brnyza** [take-i/termux-php7#1]
CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/data/data/com.termux/files/usr/bin/php"...

**Comment by brnyza** [comment]
solved using php7 directly from termux:
`apt install php7-apache`

**Comment by take-i** [comment]
I haven't tested php7-apache so much, so I'm sorry if there is a problem.
I'm glad what happened.
